### PR TITLE
Switch to attachments v4

### LINKED ISSUE #320: Attachment uploads to cdn0 are now rejected under latest Signal for ios
I noticed that Signal.app 7.26.1 (321) for ios started silently dropping my messages with attachments with this error:
```
2024/09/06 13:32:32:374  ❤ [AttachmentManagerImpl.swift:305 transitTierInfo(from:)]: assertionError: Invalid cdn info
2024/09/06 13:32:32:374  ❤ [MessageReceiver.swift:1144 processFlaglessDataMessage(_:request:thread:tx:)]: Could not build attachments!
```
Looking at the app code, it looks like ios no longer tolerates attachments that have been uploaded to cdn0:

https://github.com/signalapp/Signal-iOS/blob/7a19cb5ac898b8d5544ef3fae514b43de05182d5/SignalServiceKit/Messages/Attachments/V2/AttachmentManager/AttachmentManagerImpl.swift#L305-L308

As libsignal-server-rs only supports cdn0 currently, we'll need to add support for cdn2 and cdn3 for attachments to work going forward.

### PR DESCRIPTION
**Pull request by gferon**
which means dropping CDN0 which was AWS CloudFront and use CDN2 or CDN3 depending on what the server tells us to do.

TODO:
- [x] Make sure we still have `post_to_cdn0` functional, even though I'm not sure whether it is used or not.
- [x] Add logic for CDN2 (we cannot know whether it is still in use or not, the server tells us to use it).

In general, I'd like to ditch `libsignal-service-actix` since it is not used anymore, which in turn will let us remove the `PushService` trait and let us have a _much nicer_ direct access to the HTTP API.

Closes #320

### CODE REVIEW

File: libsignal-service-actix/src/push_service.rs [hunk 1]
```diff
@@ -579,13 +579,14 @@ impl PushService for AwcPushService {
 
     async fn post_to_cdn0<'s, C: std::io::Read + Send + 's>(
         &mut self,
+        cdn_id: u32,
```
Comment (rubdos) [inline libsignal-service-actix/src/push_service.rs:582]:
```suggestion
    async fn post_to_cdn<'s, C: std::io::Read + Send + 's>(
        &mut self,
        cdn_id: u32,
```

Comment (rubdos) [reply libsignal-service-actix/src/push_service.rs:582]: (We probably want to retain upload capability to cdn0 for profile pics etc?)

File: libsignal-service-hyper/src/push_service.rs [hunk 2]
```diff
@@ -413,6 +442,34 @@ impl PushService for HyperPushService {
...
     }
 
+    #[tracing::instrument(skip(self))]
+    async fn post(
+        &mut self,
+        service: Endpoint,
+        path: &str,
+        additional_headers: &[(&str, &str)],
+        credentials_override: HttpAuthOverride,
+    ) -> Result<HashMap<String, String>, ServiceError> {
```
Comment (rubdos) [inline libsignal-service-hyper/src/push_service.rs:452]: Post without any data?

Comment (gferon) [reply libsignal-service-hyper/src/push_service.rs:452]: yes : 😁

Comment (rubdos) [reply libsignal-service-hyper/src/push_service.rs:452]: In that case maybe
```suggestion
    #[tracing::instrument(skip(self))]
    async fn post_empty_body(
        &mut self,
        service: Endpoint,
        path: &str,
        additional_headers: &[(&str, &str)],
        credentials_override: HttpAuthOverride,
    ) -> Result<HashMap<String, String>, ServiceError> {
```
just for clarity?

Comment (rubdos) [reply libsignal-service-hyper/src/push_service.rs:452]: In that case maybe
```suggestion
    #[tracing::instrument(skip(self))]
    async fn post_empty_body(
        &mut self,
        service: Endpoint,
        path: &str,
        additional_headers: &[(&str, &str)],
        credentials_override: HttpAuthOverride,
    ) -> Result<HashMap<String, String>, ServiceError> {
```
just for clarity?

File: src/push_service/cdn.rs [hunk 3]
```diff
@@ -90,26 +116,187 @@ impl PushService {
...
+    pub(crate) async fn get_attachment_resumable_upload_url(
         &mut self,
-        attrs: AttachmentV2UploadAttributes,
-        mut reader: impl Read + Send,
-    ) -> Result<(u64, Vec<u8>), ServiceError> {
-        let attachment_id = attrs.attachment_id;
-        let mut digester =
-            crate::digeststream::DigestingReader::new(&mut reader);
+        attachment_upload_form: &AttachmentUploadForm,
+    ) -> Result<Url, ServiceError> {
```
Comment (rubdos) [inline src/push_service/cdn.rs:123]: The attachment_upload_form will be quite noisy in tracing; should we have some Display impl like I'm doing in #335 ?

File: src/push_service/cdn.rs [hunk 4]
```diff
@@ -156,4 +342,98 @@ impl PushService {
...
+    async fn upload_to_cdn3(
+        &mut self,
+        resumable_url: &Url,
+        headers: &HashMap<String, String>,
+        content_type: &str,
+        content_length: u64,
+        mut content: impl std::io::Read + std::io::Seek + Send,
+    ) -> Result<AttachmentDigest, ServiceError> {
+        let resume_info = self
+            .get_attachment_resume_info_cdn3(resumable_url, &headers)
```
Comment (rubdos) [inline src/push_service/cdn.rs:392]:
```suggestion
            .get_attachment_resume_info_cdn3(resumable_url, headers)
```

File: src/push_service/mod.rs [hunk 5]
```diff
@@ -177,15 +177,14 @@ impl PushService {
         }
     }
 
-    #[tracing::instrument(skip(self, path), fields(path = %path.as_ref()))]
+    #[tracing::instrument(skip(self))]
     pub fn request(
         &self,
         method: Method,
         endpoint: Endpoint,
```
Comment (rubdos) [inline src/push_service/mod.rs:184]: Can we have some nice display implementation for `Endpoint`, for in tracing?

File: src/push_service/cdn.rs [hunk 6]
```diff
@@ -156,4 +342,98 @@ impl PushService {
...
+    }
+
+    async fn upload_to_cdn3(
+        &mut self,
+        resumable_url: &Url,
+        headers: &HashMap<String, String>,
+        content_type: &str,
+        content_length: u64,
+        mut content: impl std::io::Read + std::io::Seek + Send,
+    ) -> Result<AttachmentDigest, ServiceError> {
```
Comment (rubdos) [inline src/push_service/cdn.rs:390]: I would add tracing::instrument here, and ensure that the parameters are quite simple. We have some tracing events in the body.

**Review by rubdos — APPROVED** [review]
Some very minor suggestions (one is clippy, easily applied). This is very pretty code, well done.

File: src/push_service/cdn.rs (hunk 6 above)
Comment (gferon) [reply src/push_service/cdn.rs:390]: Just forgot 😄 will do.

File: src/push_service/cdn.rs (hunk 3 above)
Comment (gferon) [reply src/push_service/cdn.rs:123]: I think it's ok, it's not like we upload attachments like crazy anyways.

File: src/push_service/mod.rs (hunk 5 above)
Comment (gferon) [reply src/push_service/mod.rs:184]: Done in 4e49b1bc29b1f8f8ce08bda6aecbcc384ec967a9

File: src/push_service/cdn.rs (hunk 3 above)
Comment (rubdos) [reply src/push_service/cdn.rs:123]: Maybe you don't! ;-)

**Review by rubdos — APPROVED** [review]
