### PR TITLE
Add support for PNI fields and fix fetching (encrypted groups)

### LINKED ISSUE #223: Groups v2 getAuthorizationForToday stopped working
I'll start investigating now, but I believe it might be related to PNI 😓

### PR DESCRIPTION
**Pull request by gferon**
Tested in `presage` which should get us started with #206 and fix #223.

This requires to be able to provide two separate store implementations to the underlying `libsignal`. See https://github.com/signalapp/Signal-Android/blob/b4f6177e873cfd23cbce8fdbea8b573af8faf45d/app/src/main/java/org/thoughtcrime/securesms/crypto/storage/SignalServiceAccountDataStoreImpl.java#L26 for the requirements in `Signal-Android`.

### CODE REVIEW

**Comment by gferon** [comment]
@rubdos did you investigate by any chance how one can "upgrade" an existing account and upload some PNI keypair? I don't care that much for linking, as one can simply ask to relink (without losing any data).

File: libsignal-service/src/provisioning/manager.rs [hunk 1]
```diff
@@ -271,22 +274,51 @@ impl<P: PushService> LinkingManager<P> {
...
                         )?,
                     )?;
 
+                    let pni_public_key = PublicKey::deserialize(
+                        &message.pni_identity_key_public.ok_or(
+                            ProvisioningError::InvalidData {
+                                reason: "missing public key".into(),
+                            },
+                        )?,
+                    )?;
```
Comment (rubdos) [inline libsignal-service/src/provisioning/manager.rs:312]: Should this indeed be a hard error? I imagine PNI is optional?

**Review by rubdos — COMMENTED** [review]
I have not looked into the migration logic here, no. I would rather actually implement the migration. It's not because relinking is supported in-protocol, that we can do that easily in Whisperfish already :see_no_evil:

File: libsignal-service/src/provisioning/manager.rs (hunk 1 above)
Comment (gferon) [reply libsignal-service/src/provisioning/manager.rs:312]: Yeah, this is what I thought. I can try to look into it.

Comment (gferon) [reply libsignal-service/src/provisioning/manager.rs:312]: No, it's always there.

Comment (rubdos) [reply libsignal-service/src/provisioning/manager.rs:312]: Makes sense during linking. Mergable.

**Comment by gferon** [comment]
> I have not looked into the migration logic here, no. I would rather actually implement the migration. It's not because relinking is supported in-protocol, that we can do that easily in Whisperfish already :see_no_evil: 

Yes this is what I figured. I can look into the migration, i suppose you can upload a PNI private and public key, and get some UUID back.

File: libsignal-service/src/push_service.rs [hunk 2]
```diff
@@ -67,8 +67,26 @@ pub const STICKER_PATH: &str = "stickers/%s/full/%d";
 pub const KEEPALIVE_TIMEOUT_SECONDS: Duration = Duration::from_secs(55);
 pub const DEFAULT_DEVICE_ID: u32 = 1;
 
+#[derive(Debug)]
+pub enum ServiceIdType {
+    // Account Identity
+    ACI,
+    // Phone number identity
+    PNI,
+}
```
Comment (rubdos) [inline libsignal-service/src/push_service.rs:76]:
```suggestion
#[derive(Debug)]
pub enum ServiceIdType {
    // Account Identity
    Aci,
    // Phone number identity
    Pni,
}
```

That's more rusty...

File: libsignal-service/src/push_service.rs [hunk 3]
```diff
@@ -69,17 +69,17 @@ pub const DEFAULT_DEVICE_ID: u32 = 1;
...
 #[derive(Debug)]
 pub enum ServiceIdType {
-    // Account Identity
-    ACI,
-    // Phone number identity
-    PNI,
+    /// Account Identity (an account UUID without an associated phone number, probably in the future to a username)
+    AccountIdentity,
+    /// Phone number identity (a UUID associated with a phone number)
+    PhoneNumberIdentity,
```
Comment (rubdos) [inline libsignal-service/src/push_service.rs:75]:
```suggestion
    /// Account Identity (ACI)
    ///
    /// An account UUID without an associated phone number, probably in the future to a username
    AccountIdentity,
    /// Phone number identity (PNI)
    ///
    /// A UUID associated with a phone number
    PhoneNumberIdentity,
```

**Review by rubdos — COMMENTED** [review]
Nitpick on the docstrings for the ServiceIdType.

To what extend did you look at the migration, yet?

**Comment by gferon** [comment]
> To what extend did you look at the migration, yet?

To repeat what was said on Matrix, it looks like the migration is as easy as registering pre-keys with the server for `ServiceIdType::PhoneNumberIdentity`. We should be able to merge this without changing existing behaviour, and it'll let me experiment with `presage`.
