### PR TITLE
Fix base64

### LINKED ISSUE #288: JSON Invalid Padding
Sometimes the data returned by Signal is in base64-format and not properly padded. Those errors were ignored by the `base64`-crate with version `0.13`, but the dependency update in #280 updated `base64` to `0.21` where this error is now thrown.

This is for me constantly reproducible with one group, where a missmatched device always returns invalid padded code.

To fix this, one probably has to replace every use of `BASE64_STANDARD` with `BASE64_STANDARD_NO_PAD`.

Related upstream error: <https://gitlab.com/schmiddi-on-mobile/flare/-/issues/157>. This was first noted by @boxdot in https://github.com/whisperfish/presage/pull/230#issuecomment-1899040247.

### PR DESCRIPTION
**Pull request by Schmiddiii**
Fixes #288.

Note that `BASE64_STANDARD_NO_PAD` does not work as this requires base64 to not have padding, which is also not the case for Signal. This therefore needs a custom engine.

### CODE REVIEW

**Comment by rubdos** [comment]
Seems like you miss some imports in `account_manager.rs`.

File: libsignal-service/src/utils.rs [hunk 1]
```diff
@@ -1,4 +1,18 @@
+// Signal sometimes adds padding, sometimes it does not.
+// This requires a custom decoding engine.
+// This engine is as general as possible.
+pub const BASE64: base64::engine::GeneralPurpose =
```
Comment (rubdos) [inline libsignal-service/src/utils.rs:4]: I would give this a slightly more descriptive name, like this:

```suggestion
pub const BASE64_RELAXED: base64::engine::GeneralPurpose =
```

If you want, I'll run Rust analyzer over the source and get that committed, if you don't have a rename command around.

Other name suggestions are welcome too.

Comment (Schmiddiii) [reply libsignal-service/src/utils.rs]: Renamed as desired.
